In [5]:
import pandas
import numpy
import os
import cv2

In [60]:
data_f1 = pandas.DataFrame([[2,4,6],[10,20,30]], columns=["Price" ,"Tall" ,"Value"], index = ["First" ,"second"])
d_f1 = pandas.DataFrame([{"N1": 5, "N1-2" :10 ,"N2" :12},{"N2": 5}])

In [63]:
type(data_f1)
data_f1.mean()
data_f1.Price
data_f1.max()

Price    10
Tall     20
Value    30
dtype: int64

In [8]:
print (os.listdir())
df_csv = pandas.read_csv("supermarkets.csv")
df_json = pandas.read_json("supermarkets.json")
df_xlsx = pandas.read_excel("supermarkets.xlsx")
df_txt = pandas.read_csv("supermarkets-commas.txt")
df_txt2 = pandas.read_csv("supermarkets-semi-colons.txt", sep=";")

['.config', 'supermarkets.json', 'supermarkets-semi-colons.txt', 'supermarkets-commas.txt', 'smallgray.png', 'supermarkets.csv', 'supermarkets.xlsx', 'sample_data']


In [9]:
print (os.listdir())
df_NoHeadrer = pandas.read_csv("supermarkets.csv")

['.config', 'supermarkets.json', 'supermarkets-semi-colons.txt', 'supermarkets-commas.txt', 'smallgray.png', 'supermarkets.csv', 'supermarkets.xlsx', 'sample_data']


In [86]:
#Data with no Header ,add None as header
df_NoHeadrer = pandas.read_csv("supermarkets.csv", header = None)
df_NoHeadrer.columns = ["C1", "C2", "C3", "C4", "C5", "C6", "C7"]
df_NoHeadrer.set_index("C1") # Becarefull here
# df_NoHeadrer.set_index("C1", inplace= True)

# df_NoHeadrer.set_index("C2", inplace=True) # Try this !

# df_NoHeadrer.set_index("C2", inplace=True, drop=False)
df_NoHeadrer

C1               C2             C3                C4       C5           C6  \
0  ID          Address           City             State  Country         Name   
1   1     3666 21st St  San Francisco          CA 94114      USA      Madeira   
2   2   735 Dolores St  San Francisco          CA 94119      USA  Bready Shop   
3   3      332 Hill St  San Francisco  California 94114      USA  Super River   
4   4     3995 23rd St  San Francisco          CA 94114      USA   Ben's Shop   
5   5  1056 Sanchez St  San Francisco        California      USA      Sanchez   
6   6  551 Alvarado St  San Francisco          CA 94114      USA   Richvalley   

          C7  
0  Employees  
1          8  
2         15  
3         25  
4         10  
5         12  
6         20

In [85]:
# By Label:
df_NoHeadrer = df_NoHeadrer.set_index("C2")
# df_NoHeadrer.loc["1056 Sanchez St","C6"]
# df_NoHeadrer.loc["1056 Sanchez St" :"551 Alvarado St","C5" :"C7"] # Morelabels
# df_NoHeadrer.loc[:, "C6"] # every thing from column 6; try tuple (df_NoHeadrer.loc[:, "C6"])
df_NoHeadrer

C1             C3                C4       C5           C6  \
C2                                                                           
Address          ID           City             State  Country         Name   
3666 21st St      1  San Francisco          CA 94114      USA      Madeira   
735 Dolores St    2  San Francisco          CA 94119      USA  Bready Shop   
332 Hill St       3  San Francisco  California 94114      USA  Super River   
3995 23rd St      4  San Francisco          CA 94114      USA   Ben's Shop   
1056 Sanchez St   5  San Francisco        California      USA      Sanchez   
551 Alvarado St   6  San Francisco          CA 94114      USA   Richvalley   

                        C7  
C2                          
Address          Employees  
3666 21st St             8  
735 Dolores St          15  
332 Hill St             25  
3995 23rd St            10  
1056 Sanchez St         12  
551 Alvarado St         20

In [89]:
# By indexing :
df_NoHeadrer.iloc[1:3, 3 :5]
df_NoHeadrer.iloc[1 ,:] # only raw 1
type(df_NoHeadrer.iloc[1 ,:]) # read the output
list(df_NoHeadrer.iloc[1 ,:]) # type casting to list
df_NoHeadrer

C1               C2             C3                C4       C5           C6  \
0  ID          Address           City             State  Country         Name   
1   1     3666 21st St  San Francisco          CA 94114      USA      Madeira   
2   2   735 Dolores St  San Francisco          CA 94119      USA  Bready Shop   
3   3      332 Hill St  San Francisco  California 94114      USA  Super River   
4   4     3995 23rd St  San Francisco          CA 94114      USA   Ben's Shop   
5   5  1056 Sanchez St  San Francisco        California      USA      Sanchez   
6   6  551 Alvarado St  San Francisco          CA 94114      USA   Richvalley   

          C7  
0  Employees  
1          8  
2         15  
3         25  
4         10  
5         12  
6         20

In [91]:
# Delete column by label
# 1 for column and 0 for raw
df_NoHeadrer.drop("C4", 1) 
# note it is not inpalce action
df_NoHeadrer 
df2=df_NoHeadrer.drop("C1", 1)
df2

<ipython-input-91-1a5b1cb96475>:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  df_NoHeadrer.drop("C4", 1)
<ipython-input-91-1a5b1cb96475>:6: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  df2=df_NoHeadrer.drop("C1", 1)


C2             C3                C4       C5           C6  \
0          Address           City             State  Country         Name   
1     3666 21st St  San Francisco          CA 94114      USA      Madeira   
2   735 Dolores St  San Francisco          CA 94119      USA  Bready Shop   
3      332 Hill St  San Francisco  California 94114      USA  Super River   
4     3995 23rd St  San Francisco          CA 94114      USA   Ben's Shop   
5  1056 Sanchez St  San Francisco        California      USA      Sanchez   
6  551 Alvarado St  San Francisco          CA 94114      USA   Richvalley   

          C7  
0  Employees  
1          8  
2         15  
3         25  
4         10  
5         12  
6         20

In [92]:
# Delete column by index
df_NoHeadrer.drop(df_NoHeadrer.columns [0:2],1)

<ipython-input-92-d040456d0268>:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  df_NoHeadrer.drop(df_NoHeadrer.columns [0:2],1)


C3                C4       C5           C6         C7
0           City             State  Country         Name  Employees
1  San Francisco          CA 94114      USA      Madeira          8
2  San Francisco          CA 94119      USA  Bready Shop         15
3  San Francisco  California 94114      USA  Super River         25
4  San Francisco          CA 94114      USA   Ben's Shop         10
5  San Francisco        California      USA      Sanchez         12
6  San Francisco          CA 94114      USA   Richvalley         20

In [93]:
# Delete raw by label
df_NoHeadrer.drop ("3666 21st St", 0)
df_NoHeadrer # note it is not inpalce action
df_NoHeadrer.drop ("3666 21st St", 0 ,inplace=True)

<ipython-input-93-bb78c911c9a5>:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  df_NoHeadrer.drop ("3666 21st St", 0)


KeyError: ignored

In [17]:
# Delete column by index
df_NoHeadrer.drop(df_NoHeadrer.index[0:2],0)

<ipython-input-17-87ab04a69e5d>:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  df_NoHeadrer.drop(df_NoHeadrer.index[0:2],0)


C3                C4   C5           C6  C7
C2                                                                    
332 Hill St      San Francisco  California 94114  USA  Super River  25
3995 23rd St     San Francisco          CA 94114  USA   Ben's Shop  10
1056 Sanchez St  San Francisco        California  USA      Sanchez  12
551 Alvarado St  San Francisco          CA 94114  USA   Richvalley  20

In [18]:
# Add Column
# df_NoHeadrer ["C9"] = ["Extra"] #error
len(df_NoHeadrer.index)
len(df_NoHeadrer.columns)
df_NoHeadrer ["C9"] = ["Extra", "Extra", "Extra","Extra","Extra","Extra" ]
df_NoHeadrer ["C10"]= df_NoHeadrer.shape[0] * ["More Extra"]

In [19]:
df_NoHeadrer.shape
df_NoHeadrer.shape[0]
df_NoHeadrer.shape[1]

7

In [20]:
# Modifying:
df_NoHeadrer["C10"]=" 1"
df_NoHeadrer["C10"]= df_NoHeadrer["C3"]+ "&" + "USA" # inplace operation

In [21]:
# Adding a new raw:
df3 = df_NoHeadrer.T
df3["C11"] = ["1", "2", "3", "4", "5", "6", "7"]
df3.T # not inplace opertator

C3                C4       C5           C6  \
C2                                                                       
Address                   City             State  Country         Name   
735 Dolores St   San Francisco          CA 94119      USA  Bready Shop   
332 Hill St      San Francisco  California 94114      USA  Super River   
3995 23rd St     San Francisco          CA 94114      USA   Ben's Shop   
1056 Sanchez St  San Francisco        California      USA      Sanchez   
551 Alvarado St  San Francisco          CA 94114      USA   Richvalley   
C11                          1                 2        3            4   

                        C7     C9                C10  
C2                                                    
Address          Employees  Extra           City&USA  
735 Dolores St          15  Extra  San Francisco&USA  
332 Hill St             25  Extra  San Francisco&USA  
3995 23rd St            10  Extra  San Francisco&USA  
1056 Sanchez St         12  Extra  San Francisco&USA  
551 Alvarado St         20  Extra  San Francisco&USA  
C11                      5      6                  7

In [35]:
import geopy
from geopy.geocoders import ArcGIS
nom = ArcGIS() 
nom.geocode("Baross utca,Budapest, Hu 1083")

Location(1083, Józsefváros, Budapest 8, Budapest, Baross utca, (47.48890571886804, 19.082471289268923, 0.0))

Your task is to add two columns. One for the latitude and one for the longitude.
Note: with the structure of type series
you cannot use any methods, only you
can use apply function.

In [56]:
add = pandas.read_csv("supermarkets.csv") 
add['Locations']= (add['Address']+","+add["City"]+","+add['State']+','+add["Country"]).apply(nom.geocode)
# Adds Latitude column
add['Latitude'] = add['Locations'].apply(lambda x: x.latitude if x else None)
# Adds Latitude column
add['Longitude'] = add['Locations'].apply(lambda x: x.longitude if x else None)

add

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees                                          Locations   Latitude  \
0          8  (3666 21st St, San Francisco, California, 9411...  37.756632   
1         15  (735 Dolores St, San Francisco, California, 94...  37.757829   
2         25  (332 Hill St, San Francisco, California, 94114...  37.755845   
3         10  (3995 23rd St, San Francisco, California, 9411...  37.752921   
4         12  (1056 Sanchez St, San Francisco, California, 9...  37.752132   
5         20  (551 Alvarado St, San Francisco, California, 9...  37.753582   

    Longitude  
0 -122.429411  
1 -122.425373  
2 -122.428813  
3 -122.431703  
4 -122.430006  
5 -122.433234

In [57]:
n = numpy.arange(27)
n # Type(n)
n.reshape(3, 9)
n # Type(n)
n.reshape(3, 3, 3) 
n # Type(n)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [58]:
# Note: 0 for grey image
# 1 for BGR image
im = cv2.imread("smallgray.png", 0)
type(im)

numpy.ndarray

In [26]:
# If you have an array and you
# want to change it to image.
cv2.imwrite("newsmallgrey.png", im)

True

In [27]:
# Access elements # concept [X,Y]
im = cv2.imread("smallgray.png",0)
im[0:2]
im[0:2,2:4]
im.shape
help(numpy.shape)
im[:,3:4]
im[2,4]
im[0,4]

Help on function shape in module numpy:

shape(a)
    Return the shape of an array.
    
    Parameters
    ----------
    a : array_like
        Input array.
    
    Returns
    -------
    shape : tuple of ints
        The elements of the shape tuple give the lengths of the
        corresponding array dimensions.
    
    See Also
    --------
    len
    ndarray.shape : Equivalent array method.
    
    Examples
    --------
    >>> np.shape(np.eye(3))
    (3, 3)
    >>> np.shape([[1, 2]])
    (1, 2)
    >>> np.shape([0])
    (1,)
    >>> np.shape(0)
    ()
    
    >>> a = np.array([(1, 2), (3, 4)], dtype=[('x', 'i4'), ('y', 'i4')])
    >>> np.shape(a)
    (2,)
    >>> a.shape
    (2,)



0

In [29]:
# Iterate using Numpy
for i in im:
  print(i)

# for i in im.T:
#   print(i)

# for i in im.flat:
#   print(i)

[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ...

In [59]:
# Stacking with numpy
# im_stack=numpy.hstack(im, im)#error
# help(numpy.hstack)
im_stack=numpy.hstack((im, im)) # type(im_stack)
# Split array with numpy
lst=numpy.hsplit(im_stack,2) 
# lst=numpy.vsplit(im,3)
# type(lst)